Create OpenAccountController
Nosto/nosto-prestashop pull request #331
Opened 2022-08-02 07:19 UTC by dairbuirabass

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Documentation:

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] I have assigned the correct milestone or created one if non-existent.
- [ ] I have correctly labeled this pull request.
- [ ] I have linked the corresponding issue in this description.
- [ ] I have updated the corresponding Jira ticket.
- [ ] I have requested a review from at least 2 reviewers
- [ ] I have checked the base branch of this pull request
- [ ] I have checked my code for any possible security vulnerabilities

2022-08-15 10:56 UTC, supercid approved these changes
Looks good. Can you deploy to plugintest so we can test?

2022-08-15 10:56 UTC, supercid commented on composer.json
> +    "nosto/php-sdk": "dev-feature/remove-iframe-prestashop",
Remember to update this one before merging it

2022-08-15 10:56 UTC, supercid commented on controllers/admin/NostoIndexController.php
> +            if (Tools::getValue(NostoSDK::URL_PARAM_MESSAGE_TYPE) === NostoSDK::TYPE_SUCCESS) {
You can combine those two if's to reduce nesting

2022-08-15 11:01 UTC, supercid requested changes
We need to have a look at this error though: 
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/2778820/184624089-988b76be-e6b3-4dec-b055-0d9e2c7eb95d.png">

2022-08-16 10:47 UTC, dairbuirabass commented on composer.json
> +    "nosto/php-sdk": "dev-feature/remove-iframe-prestashop",
Updated. Merging the PR

2022-08-16 10:48 UTC, dairbuirabass commented
> We need to have a look at this error though: <img alt="image" width="1193" src="https://user-images.githubusercontent.com/2778820/184624089-988b76be-e6b3-4dec-b055-0d9e2c7eb95d.png">

This should be resolved now.

2022-08-16 10:48 UTC, supercid approved these changes

2022-08-16 10:53 UTC, merged