Bump version, update CHANGELOG.md
Nosto/nosto-prestashop pull request #346
Opened 2022-11-15 09:46 UTC by dairbuirabass

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Documentation:

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] I have assigned the correct milestone or created one if non-existent.
- [x] I have correctly labeled this pull request.
- [x] I have linked the corresponding issue in this description.
- [x] I have updated the corresponding Jira ticket.
- [x] I have requested a review from at least 2 reviewers
- [x] I have checked the base branch of this pull request
- [x] I have checked my code for any possible security vulnerabilities

2022-11-15 09:47 UTC, supercid requested changes
Check the base

2022-11-15 11:47 UTC, supercid commented on nostotagging.php
> +        $this->ps_versions_compliancy = array('min' => '1.5.5.0', 'max' => '8.0.0');
Maybe we should:
```suggestion
        $this->ps_versions_compliancy = array('min' => '1.5.5.0', 'max' < '8.1.0');
```

2022-11-15 11:47 UTC, supercid commented on nostotagging.php
> +        $this->ps_versions_compliancy = array('min' => '1.5.5.0', 'max' => '8.0.0');
or wait, is that even correct?

2022-11-15 11:47 UTC, dairbuirabass commented on nostotagging.php
> +        $this->ps_versions_compliancy = array('min' => '1.5.5.0', 'max' => '8.0.0');
Just in case of a future release? Makes sense.

2022-11-15 11:48 UTC, dairbuirabass commented on nostotagging.php
> +        $this->ps_versions_compliancy = array('min' => '1.5.5.0', 'max' => '8.0.0');
Yeah, that's the versioning now 😄

2022-11-15 11:49 UTC, supercid commented on nostotagging.php
> +        $this->ps_versions_compliancy = array('min' => '1.5.5.0', 'max' => '8.0.0');
I mean, we should support anything lower than 8.1.0, but I'm not sure how this max flag works, the logic might be inverted there

2022-11-15 11:50 UTC, dairbuirabass commented on nostotagging.php
> +        $this->ps_versions_compliancy = array('min' => '1.5.5.0', 'max' => '8.0.0');
It's an array, not a comparison operator

2022-11-15 11:50 UTC, dairbuirabass commented on nostotagging.php
> +        $this->ps_versions_compliancy = array('min' => '1.5.5.0', 'max' => '8.0.0');
https://devdocs.prestashop-project.org/1.7/modules/concepts/module-class/#ps_versions_compliancy

2022-11-15 11:51 UTC, supercid commented on nostotagging.php
> +        $this->ps_versions_compliancy = array('min' => '1.5.5.0', 'max' => '8.0.0');
You're right.
Enough coding for me today 😂

2022-11-15 11:53 UTC, dairbuirabass commented on nostotagging.php
> +        $this->ps_versions_compliancy = array('min' => '1.5.5.0', 'max' => '8.0.0');
😆 but I will change it to `8.1.0` just to avoid re-releasing only for the sake of module being installable.

2022-11-16 07:31 UTC, supercid approved these changes

2022-11-16 10:21 UTC, merged